name: Deploy Bicep files

trigger: none
# - main

variables:
  resourceGroupName: 'rg-bicep-demo-0017'
  location: 'westeurope'
  webAppName: 'bicep00105'
  templateFile: '01-bicep-webapp/webapp-linux.bicep'
  Subscription: 'Azure subscription 1 (38f51217-7342-4f22-b591-b19d85f1504d)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  displayName: 'Cache'
  inputs:
    key: $(Build.SourcesDirectory)/cache.json
    path: '$(npm_config_cache)'
    cacheHitVar: 'CACHE_RESTORED'
- task: AzureCLI@2
  displayName: Preview Bicep Changes
  inputs:
    azureSubscription: $(Subscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
            az group create --name $(resourceGroupName) --location $(location)
            az deployment group what-if --resource-group $(resourceGroupName) \
              --template-file $(templateFile) \
              --parameters webAppName=$(webAppName)
# - task: AzureCLI@2
#   displayName: Preview Bicep Changes
#   inputs:
#     azureSubscription: 'Microsoft-Azure-0(17b12858-3960-4e6f-a663-a06fdae23428)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az --version
#       az group create --name $(resourceGroupName) --location $(location)
#       az deployment group what-if --resource-group $(resourceGroupName) \
#          --template-file $(templateFile) \
#          --parameters webAppName=$(webAppName)
- task: AzureResourceManagerTemplateDeployment@3
  condition: ne(variables.CACHE_RESTORED, 'true')
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 (38f51217-7342-4f22-b591-b19d85f1504d)'
    subscriptionId: '38f51217-7342-4f22-b591-b19d85f1504d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-bicep-demo-0017'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '01-arm-template-webapp/webapp-linux.json'
    csmParametersFile: '01-arm-template-webapp/azuredeploy.parameters.json'
    #overrideParameters: '--parameters webAppName=$(webAppName)'
    deploymentMode: 'Incremental'
    workingDir: '$(Build.SourcesDirectory)/cache.json'  

# - task: AzureCLI@2
#   displayName: Deploy Bicep To Azure
#   inputs:
#     azureSubscription: $(Subscription)
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az deployment group create --resource-group $(resourceGroupName) \
#          --template-file $(templateFile) \
#          --parameters webAppName=$(webAppName)
